import pytest

def add(a, b):
    return a + b

def test_add():
    assert add(2, 3) == 5
""" Role Explanation 
 **Test Runner

Executes test cases

Example: pytest

Runs all tests automatically

 **Test Reports

Show test results (pass/fail)

Help analyze test execution

Generated by pytest plugins

** Configuration Files

Store environment settings

Avoid hardcoding values

Example: URLs, browser type"""