# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

class TestTc003():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tc003(self):
    self.driver.get("https://demo.opencart.com/")
    self.driver.set_window_size(1296, 688)

    self.driver.find_element(By.CSS_SELECTOR, ".fa-bars").click()
    self.driver.find_element(By.LINK_TEXT, "Desktops").click()
    self.driver.find_element(By.LINK_TEXT, "Mac (1)").click()

    self.driver.find_element(By.ID, "input-sort").click()
    dropdown = self.driver.find_element(By.ID, "input-sort")
    dropdown.find_element(By.XPATH, "//option[. = 'Name (A - Z)']").click()

    self.driver.find_element(By.CSS_SELECTOR, ".image .img-fluid").click()
    self.driver.find_element(By.ID, "button-cart").click()
